package com.martinus.wisataku

object WisataData {
    private val tempatWisata = arrayOf(
        "BALI",
        "Raja Ampat",
        "Tana Toraja",
        "Pulau Komodo",
        "Candi Borobudur",
        "Taman Laut Bunaken",
        "Danau Sentani",
        "Kepulauan Karimunjawa",
        "Gunung Bromo",
        "Taman Nasional Wakatobi",
    )

    private val wisataDetail = arrayOf(
        "Pulau Bali, merupakan pulau yang berada di kawasan Negara Kesatuan Republik Indonesia dan paling terkenal di hampir penjuru Dunia. Pulau ini menyimpan keindahan alam dan keunikan budaya yang masih melekat hingga saat ini. Selain itu keramah tamahan dari penduduknya juga menjadi ciri khas dari Pulau Bali, dan bisa membuat kita betah berlama - lama berwisata ke destinasi yang berjuluk Pulau Dewata ini. Budaya di Bali memang bisa dikatakan terlestarikan dari generasi ke generasi, bukan karena banyaknya wisatawan yang mengunjunginya, melainkan memang komitmen dari warga Bali yang akan terus mempertahankan kebudayaanya sehingga menjadi ciri khas dari Bali sendiri. Sebagai tempat wisata yang paling terkenal di Indonesia, dan mempunyai resort yang dipadu dengan keindahan pantai yang mempesona, serta gemerlap kehidupan malamnya, menjadikan Pulau Bali sebagai tempat wisata terbaik Dunia ( World's Best Island ) versi Majalah Travel pada tahun 2009. Dan ditahun 2010 juga memperoleh penghargaan dengan peringkat ke dua Best of Travel 2010 versi Majalah Leasure. Julukan dari Bali sendiri bermacam - macam, ada yang mengenal Bali sebagai pulau Dewata, pulau surga dan ada pula yang menjulukinya sebagai pulau seribu pura. Pesona alam yang sangat luar biasa seperti hamparan sawah yang menghijau dan memberikan ketenangan dan rasa damai, gunung berapi yang menjulang dan tampak dekat dan besar, serta keindahan pantai dan hamparan pasirnya yang mengagumkan membuat kerinduan tersendiri menjelang meninggalkan Bali.",
        "Kepulauan Raja Ampat merupakan destinasi wisata yang terletak di wilayah Papua. Wisata ini sudah dikenal oleh seluruh dunia karena keindahan alamnya yang sangat mempesona. Salah satu hal yang mengangkat nama objek wisata Raja Ampat adalah dengan adanya film dokumenter yang dibuat oleh Avant Premiere dengan judul “Edis Paradise 3”, dimana dalam film tersebut menceritakan keindahan alam bawah laut Raja Ampat yang berada di kawasan Papua. Kawasan wisata Raja Ampat saat ini dijuluki sebagi kawasan Amazon Lautan Dunia. Julukan tersebut diberikan karena letak dari tempat wisata ini yang berada dipusat segitiga karang dunia. Wisata Kepulauan Raja Ampat berada dikawasan teritorial Papua Barat, yang merupakan sebuah gugusan pulau yang tersebar dengan jumlahnya berkisar 610 pulau, akan tetapi hanya ada 35 pulau yang dihuni oleh penduduk. Para wisatawan yang berasal dari penjuru dunia sengaja datang kesini untuk menikmati keindahan pulau dan keunikan wisata bawah lautnya, serta menjelajahi dinding – dinding bawah laut dengan cara menyelam. Disini wisatawan juga bisa mengarungi gugusan kepulauan besar dan kecil, pegunungan, hutan tropis, untaian karang laut, pantai pasir putih serta keaneka ragaman kehidupan satwa yang ada di kawasan wisata Raja Ampat. Memang boleh dikatakan kalau kekayaan alam seperti ini sangat jarang sekali ada, jadi bersyukur sekali apabila Indonesia memiliki anugrah yang sulit untuk dilukiskan dengan kata – kata.",
        "Tana Toraja. Destinasi ini memang sangat menarik untuk dikunjungi, budayanya yang masih kental membuat magnet tersendiri bagi para wisatawan baik itu yang berasal dari dalam maupun luar negeri. memang bagi Anda yang baru mengunjungi Tana Toraja kesan mistis sangat terasa, tetapi dibalik itu semua pemandangan alam yang ada di Tana Toraja akan membuat Anda terhipnotis dan ingin berlama - lama menikmatinya. Secara geografis Tana Toraja merupakan sebuah kabupaten yang berada di kawasan provinsi Sulawesi Utara, dan ibukota dari Tana Toraja berada di Makale. Masyarakat suku Toraja sendiri masih memegang teguh keyakinan dan gaya hidup yang khas mirip sekali dengan budaya yang ada di Nias, yang menjadikan Tana Toraja menjadi salah satu situs warisan budaya dunia yang terdaftar di UNESCO. Masyarakat Tana Toraja sendiri banyak menggelar upacara adat yang didalamnya menyuguhkan berbagai tarian serta atraksi yang sangat menarik, dan bagi Anda pencinta seni pastinya tidak menyianyiakan kesempatan tersebut. selain itu disini juga terdapat rumah adat yang sangat unik yang hanya ada di Tana Toraja.",
        "Di antara sekian pulau yang ada di Kepulauan Nusa Tenggara, ada sebuah pulau yang menarik untuk kita jujuki. Namanya Pulau Komodo. Sesuai dengan namanya, Pulau Komodo merupakan pulau yang juga menjadi habitat hewan langkah di negeri ini. Keberadaannya makin tahun makin menyusut. Tentu mengasyikkan bila kita bisa melihat langsung kehidupan hewan yang dilindungi negara ini. Bukan hanya di Pulau Komodo, habitat komodo juga ada di pulau yang berdekatan dengannya. Seperti di Pulau Rinca. Di pulau tersebut, wisatawan bisa leluasa melihat dan mengamati pola keseharian komodo. Terdapat tempat yang tepat untuk melihat kawanan komodo. Wisatawan bisa mendaki sebuah bukit, yaitu Bukit Ara (538 mdpl). Di atas gunung itu, kawanan komodo banyak hidup secara liar. Selain komodo, satwa lain yang bisa kita lihat, yaitu rusa liar, banteng dan kuda liar",
        "Selain mengunjungi wisata alam yang indah di Jogja, para turis biasanya menyempatkan diri untuk mengunjungi tempat wisata Candi Borobudur, baik itu turis domestik, apalagi turis asing. Emang sekeren apa sih tempat ini? Tak hanya bangunannya saja yang megah, relief relief yang tergurat di candinya pun menyiratkan beragam makna terpendam yang membuat penasaran semua orang yang melihatnnya. Belum lagi adanya mitos tentang danau purba. Tak heran kalau situs bersejarah ini sangat terkenal di dunia dan masuk dalam 7 Keajaiban Dunia.",
        "Taman Nasional Bunaken merupakan tempat wisata yang berada di Teluk Manado - Sulawesi Utara dengan luas sekitar 8,08 km persegi, tempat wisata ini merupakan salah satu bagian dari pemeritahan kota Manado yang merupakan ibukota Sulawesi Utara. di sini terdapat sebuah Taman Laut yang sangat indah yang terdapat di sekitar pulau Manado Tua ( Mantehage dan Siladen ). untuk menikmati suasana bawah laut Bunaken Anda harus menyelam kedalam dan bergerak mengikuti irama ombak yang mengalir. Pesona alam bawah laut yang menakjubkan akan dapat anda temukan disini, ada sekitar 13 jenis terumbu karang  yang menjulang terjal vertikal kebawah sedalam sekitar 25 - 50 meter. Anda juga akan dimanjakan dengan pemandangan yang disuguhkan oleh sekitar 91 species ikan yang ada di Taman Laut Bunaken.",
        "Danau Sentani berada tak jauh dari pusat ibukota Provinsi Papua, yaitu Jayapura. Danau ini menyimpan berbagai pesona mengesankan yang tak akan terlupakan. Berbagai keunikan bentuk alam dan budaya menjadi identitas tersendiri, sehingga tempat ini wajib dimasukkan dalam daftar destinasi wisata Anda. Pertunjukan yang seringkali menyita perhatian para wisatawan untuk datang ke Danau Sentani adalah adanya sebuah festival. Festival Danau Sentani diselenggarakan setiap tanggal 19 Juni sebagai bentuk pelestarian kebudayaan sekaligus memperlihatkan hubungan keharmonisan dan persatuan warga setempat. Papua memang dikenal sebagai daerah yang cukup sering terjadi konflik antar suku, sehingga perdamaian harus diwujudkan melalui festival Danau Sentani ini. Adapun peserta yang mengikuti festival terdiri dari seluruh paguyuban yang berada di wilayah Kota maupun Kabupaten Jayapura. Anda akan melihat pertunjukkan yang memadukan kebudayaan asli Tabi, dimana daerah tersebut memiliki 16 sub suku dan sumber daya alam terbaik. Terkadang dalam festival ini akan dijumpai pula penampakan buaya, tapi tidak selalu ada. Anda bisa menangkap momen ini jika beruntung.Sedangkan rangkaian acara festival Danau Sentani akan dimulai dengan tarian adat yang dipraktekkan di atas perahu. Setelah itu berlanjut pada tarian perang khas Papua, kemudian upacara adat guna menobatkan Ondoafi (pemimpin adat asli Sentani). Lalu yang terakhir adalah menikmati berbagai macam sajian kuliner khas Papua.",
        "Kepulauan Kerimun jawa menawarkan wisata bahari dan alam yang indah dan menawan untuk wisatawan domestik dan mancanegara. Nama Karimunjawa sendiri berasal dari dari sebuah cerita rakyat sekitar. Konon dulu Sunan Muria membuang anaknya yang nakal yang bernama Syekh Amir Hasar ke pulau yang kremun-kremun dalam bahasa Jawa, yang artinya samar-samar. Karena tampak kremun-kremun maka pulau ini dinamakan pulau Karimun dan kini pulau tersebut akrab dikenal dengan nama Karimunjawa. Pulau yang dijadikan Taman Nasional pada bulan Maret 2001 ini merupakan rumah bagi terumbu karang, hutan bakau, hutan pantai dan ratusan spesies fauna laut yang lebih dari 200 jenis diantaranya merupakan jenis ikan hias. Kepulauan ini juga merupakan rumah bagi beberapa hewan langka seperti Elang Laut Dada Putih, penyu sisik dan penyu hijau. Keistimewaan lainnya dari kepulauan ini adalah tumbuhan Dewandaru yang hanya terdapat di kepulauan ini dan tidak ada di tempat lain. Anda tidak dianjurkan untuk memetik dan membawa pulang tumbuhan ini bila berkunjung ke Karimunjawa karena menurut cerita rakyat sekitar bila Anda melakukannya maka kapal yang Anda tumpangi akan tenggelam. Kepulauan yang mayoritas memiliki pasir putih halus ini memang menyimpan keindahan alam yang selalu menarik minat para wisatawan.",
        "Kawasan wisata yang menjadi ikon Jawa Timur ini menjadi impian bagi semua orang. Bagaimana tidak, pesona matahari terbit yang sudah di dengar hingga ke berbagai penjuru di dunia ini menjadi sajian utama yang tidak boleh terlewatkan bila wisatawan berkunjung ke kawasan ini. Perjuangan panjang yang harus bangun pukul 3 pagi menjadi salah satu kenangan yang tidak akan terlupakan. Sementara pada pukul 3 pagi, kawasan bromo begitu dingin. Bila beruntung sobat bisa merasakan suhu yang mencapai titik 0 derajat. ",
        "Taman nasional Wakatobi merupakan salah satu surga bawah laut paling indah di dunia. Kabupaten Wakatobi terdiri dari empat pulau utama, yaitu Wangiwangi, Kalidupa, Tomia, dan Binongko. Nama Wakatobi merupakan akronim dari empat pulau utama itu.  WAngi-Wangi, KAledupa, TOmia, dan BInongko. Selain keempat pulau tersebut, terdapat beberapa pulau kecil lain yang berada di wilayah Wakatobi, antara lain Pulau Hoga, Kapota, Anano dan Rundumana. Taman Nasional Wakatobi yang ditetapkan pada tahun 1996, dengan total area 1,39 juta hektar, menyangkut keanekaragaman hayati laut dan karang yang menempati salah satu posisi prioritas tertinggi dari konservasi laut di Indonesia. Keindahan dan kekayaan kawasan Taman Nasional Wakatobi sebenarnya sudah terkenal di mancanegara, terutama setelah Ekspedisi Wallacea dari Inggris pada tahun 1995 yang menyebutkan bahwa kawasan di Sulawesi Tenggara ini sangat kaya akan spesies koral. Di Taman Nasional Wakatobi terdapat 750 dari total 850 spesies koral yang ada di dunia. Konfigurasi kedalamannya bervariasi mulai dari datar sampai melandai ke laut dan di beberapa daerah perairan terdapat yang bertebing  curam. Bagian terdalam perairannya mencapai 1.044 meter."
    )

    private val wisataImage = intArrayOf(
        R.drawable.bali,
        R.drawable.raja_ampat,
        R.drawable.tana_toraja,
        R.drawable.pulau_komodo,
        R.drawable.candi_borobudur,
        R.drawable.taman_laut_bunaken,
        R.drawable.danau_sentani,
        R.drawable.kepulauan_karimunjawa,
        R.drawable.gunung_bromo,
        R.drawable.taman_nasional_wakatobi
    )

    val listData: ArrayList<Wisata>
        get() {
            val list = arrayListOf<Wisata>()
            for (position in tempatWisata.indices) {
                val wisata = Wisata()
                wisata.name = tempatWisata[position]
                wisata.detail = wisataDetail[position]
                wisata.photo = wisataImage[position]
                list.add(wisata)
            }
            return list
        }
}